#pragma once

namespace game
{

// MOUSE CURSOR
extern const char SpriteFileCursor[];

// DIALOG END MISSION
extern const char SpriteFileDialogEndMission[];

enum SpriteIdDialogEndMission : unsigned int
{
    // BACKGROUND
    ID_DIA_ENDM_BG_L,
    ID_DIA_ENDM_BG_R,
};

extern const char SpriteFileDialogEndMissionExp[];

// DIALOG EXIT
extern const char SpriteFileDialogExit[];

enum SpriteIdDialogExit : unsigned int
{
    // BACKGROUND
    ID_DLG_EXIT_BG_TOP,
    ID_DLG_EXIT_BG_BOT,
    // BUTTON WISHLIST
    ID_DLG_EXIT_BTN_WL_NORMAL,
    ID_DLG_EXIT_BTN_WL_OVER,
    ID_DLG_EXIT_BTN_WL_PUSHED,
    // ICONS
    ID_DLG_EXIT_ICON_STEAM,
};

extern const char SpriteFileDialogExitExp[];

// DIALOG EXPLORE TEMPLE
extern const char SpriteFileDialogExploreTemple[];

enum SpriteIdDialogExploreTemple : unsigned int
{
    // BACKGROUND
    ID_DLG_EXTM_BACKGROUND,
    ID_DLG_EXTM_LINE_H,
    ID_DLG_EXTM_LINE_V,

    // BUTTON
    ID_DLG_EXTM_BTN_NORMAL,
    ID_DLG_EXTM_BTN_DISABLED,
    ID_DLG_EXTM_BTN_OVER,
    ID_DLG_EXTM_BTN_PUSHED,

    // ICONS
    ID_DLG_EXTM_ICON_MONEY,
    ID_DLG_EXTM_ICON_MATERIAL,
    ID_DLG_EXTM_ICON_BLOBS,
    ID_DLG_EXTM_ICON_DIAMONDS,

    // SLIDER
    ID_DLG_EXTM_SLIDER_BG,
    ID_DLG_EXTM_SLIDER_BAR,
    ID_DLG_EXTM_SLIDER_BTN,
};

// DIALOG MISSION GOALS
extern const char SpriteFileDialogMissionGoals[];

enum SpriteIdDialogMissionGoals : unsigned int
{
    // BACKGROUNDS
    ID_DLG_MGOALS_BG_TOP,
    ID_DLG_MGOALS_BG_BOTTOM,

    // BUTTON COLLECT
    ID_DLG_MGOALS_BTN_COLLECT_NORMAL,
    ID_DLG_MGOALS_BTN_COLLECT_DISABLED,
    ID_DLG_MGOALS_BTN_COLLECT_OVER,
    ID_DLG_MGOALS_BTN_COLLECT_PUSHED,

    // BUTTON END MISSION
    ID_DLG_MGOALS_BTN_END_NORMAL,
    ID_DLG_MGOALS_BTN_END_DISABLED,
    ID_DLG_MGOALS_BTN_END_OVER,
    ID_DLG_MGOALS_BTN_END_PUSHED,
};

extern const char SpriteFileDialogMissionGoalsExp[];

enum SpriteIdDialogMissionGoalsExp : unsigned int
{
    // BACKGROUND
    ID_DLG_MGOALS_BG_MID,
    // PANELS ROW
    ID_DLG_MGOALS_BG_ROW1,
    ID_DLG_MGOALS_BG_ROW2,
    // SECTION HORIZONTAL LINE
    ID_DLG_MGOALS_SECTION_LINE,

};

// NEW ELEMENT DIALOG
extern const char SpriteFileDialogNewElement[];

enum SpriteIdDialogNewElement : unsigned int
{
    // BACKGROUNDS
    ID_DLG_NEWE_U_BG_L,
    ID_DLG_NEWE_U_BG_R,
    ID_DLG_NEWE_S_BG_L,
    ID_DLG_NEWE_S_BG_R,
    ID_DLG_NEWEL_PAN_IMG_NORMAL,
    ID_DLG_NEWEL_PAN_IMG_DISABLED,
    ID_DLG_NEWEL_PAN_IMG_OVER,
    ID_DLG_NEWEL_PAN_IMG_CHECKED,
    ID_DLG_NEWEL_PAN_INFO,
    // BUTTON LEFT
    ID_DLG_NEWEL_LEFT_NORMAL,
    ID_DLG_NEWEL_LEFT_DISABLED,
    ID_DLG_NEWEL_LEFT_OVER,
    ID_DLG_NEWEL_LEFT_PUSHED,
    // BUTTON RIGHT
    ID_DLG_NEWEL_RIGHT_NORMAL,
    ID_DLG_NEWEL_RIGHT_DISABLED,
    ID_DLG_NEWEL_RIGHT_OVER,
    ID_DLG_NEWEL_RIGHT_PUSHED
};

extern const char SpriteFileDialogNewElementExp[];

enum SpriteIdDialogNewElementExp : unsigned int
{
    // BACKGROUND
    ID_DLG_NEWE_U_BG_C,
    ID_DLG_NEWE_S_BG_C,
};

// NEW MINI UNITS SQUAD DIALOG
extern const char SpriteFileDialogNewMiniUnits[];

// DIALOG OBJECT
extern const char SpriteFileDialogObject[];

enum SpriteIdDialogObject : unsigned int
{
    // BACKGROUND
    ID_DLG_OBJ_BG_L,
    ID_DLG_OBJ_BG_R,
    // PANEL BACKGROUND
    ID_DLG_OBJ_PANEL_BG_L,
    ID_DLG_OBJ_PANEL_BG_R,
};

extern const char SpriteFileDialogObjectExp[];

enum SpriteIdDialogObjectExp : unsigned int
{
    // BACKGROUND
    ID_DLG_OBJ_BG_C,
    // PANEL BACKGROUND
    ID_DLG_OBJ_PANEL_BG_C,
};

// DIALOG RESEARCH
extern const char SpriteFileDialogResearch[];

enum SpriteIdDialogResearch : unsigned int
{
    // BACKGROUND
    ID_DLG_RES_BG_L,
    ID_DLG_RES_BG_R,
};

extern const char SpriteFileDialogResearchExp[];

// DIALOG TECH TREE
extern const char SpriteFileDialogTechTree[];

enum SpriteIdDialogTechTree : unsigned int
{
    // BACKGROUND
    ID_DLG_TECHT_BG_L,
    ID_DLG_TECHT_BG_R,
    // BUTTON SECTION
    ID_DLG_TECHT_BTN_SEC_NORMAL,
    ID_DLG_TECHT_BTN_SEC_OVER,
    ID_DLG_TECHT_BTN_SEC_PUSHED,
    ID_DLG_TECHT_BTN_SEC_CHECKED,
    // BUTTON UNLOCK
    ID_DLG_TECHT_BTN_UNL_NORMAL,
    ID_DLG_TECHT_BTN_UNL_DISABLED,
    ID_DLG_TECHT_BTN_UNL_OVER,
    ID_DLG_TECHT_BTN_UNL_PUSHED,
    // BUTTON UPGRADE
    ID_DLG_TECHT_BTN_UPG_NORMAL,
    ID_DLG_TECHT_BTN_UPG_DISABLED,
    ID_DLG_TECHT_BTN_UPG_OVER,
    ID_DLG_TECHT_BTN_UPG_PUSHED,
    ID_DLG_TECHT_BTN_UPG_CHECKED,
    ID_DLG_TECHT_BTN_UPG_LVL_BG,
    // UPGRADE UNLOCKED
    ID_DLG_TECHT_UPG_UNLOCKED,
    // CONNECTIONS
    ID_DLG_TECHT_LINK_VS,
    ID_DLG_TECHT_LINK_VL,
    ID_DLG_TECHT_LINK_HS,
    ID_DLG_TECHT_LINK_HL,
    // ICONS UPGRADES
    ID_TECH_UP_ICON_TODO,
    ID_TECH_UP_ICON_BASE_IMPROVE,
    ID_TECH_UP_ICON_RADAR_STATION,
    ID_TECH_UP_ICON_RADAR_TOWER,
    ID_TECH_UP_ICON_STORAGE_STRUCTS,
    ID_TECH_UP_ICON_STORAGE_ENERGY,
    ID_TECH_UP_ICON_STORAGE_MATERIAL,
    ID_TECH_UP_ICON_STORAGE_DIAMONDS,
    ID_TECH_UP_ICON_STORAGE_BLOBS,
};

extern const char SpriteFileDialogTechTreeExp[];

// DIALOG TRADING
extern const char SpriteFileDialogTrading[];

enum SpriteIdDialogTrading : unsigned int
{
    // BACKGROUNDS
    ID_DLG_TRADING_BG_L,
    ID_DLG_TRADING_BG_R,
    ID_DLG_TRADING_BG_HEADER1,
    ID_DLG_TRADING_BG_HEADER2,
    // BUTTON BUY
    ID_DLG_TRADING_BTN_BUY_NORMAL,
    ID_DLG_TRADING_BTN_BUY_DISABLED,
    ID_DLG_TRADING_BTN_BUY_OVER,
    ID_DLG_TRADING_BTN_BUY_PUSHED,
    // BUTTON SELL
    ID_DLG_TRADING_BTN_SELL_NORMAL,
    ID_DLG_TRADING_BTN_SELL_DISABLED,
    ID_DLG_TRADING_BTN_SELL_OVER,
    ID_DLG_TRADING_BTN_SELL_PUSHED,
    // BUTTON MINUS
    ID_DLG_TRADING_BTN_MINUS_NORMAL,
    ID_DLG_TRADING_BTN_MINUS_DISABLED,
    ID_DLG_TRADING_BTN_MINUS_OVER,
    ID_DLG_TRADING_BTN_MINUS_PUSHED,
    // BUTTON PLUS
    ID_DLG_TRADING_BTN_PLUS_NORMAL,
    ID_DLG_TRADING_BTN_PLUS_DISABLED,
    ID_DLG_TRADING_BTN_PLUS_OVER,
    ID_DLG_TRADING_BTN_PLUS_PUSHED,
};

extern const char SpriteFileDialogTradingExp[];

enum SpriteIdDialogTradingExp : unsigned int
{
    // BACKGROUND
    ID_DLG_TRADING_BG_C,
    ID_DLG_TRADING_BG_ROW,
    // LINE
    ID_DLG_TRADING_LINE
};

// DIALOG UPGRADE
extern const char SpriteFileDialogUpgrade[];

enum SpriteIdDialogUpgrade : unsigned int
{
    // DIALOG
    ID_DLG_UP_BG_L,
    ID_DLG_UP_BG_R,
    ID_DLG_UP_ATT_BG,
    ID_DLG_UP_ATT_DISABLED_BG,
    ID_DLG_UP_PANELS_BG,
    // VALUE BAR
    ID_DLG_UP_VAL_BAR_PIP_OFF,
    ID_DLG_UP_VAL_BAR_PIP_ON,
    ID_DLG_UP_VAL_BAR_PIP_NEW,
    // BUTTON -
    ID_DLG_UP_BTN_MINUS_NORMAL,
    ID_DLG_UP_BTN_MINUS_DISABLED,
    ID_DLG_UP_BTN_MINUS_OVER,
    ID_DLG_UP_BTN_MINUS_PUSHED,
    // BUTTON +
    ID_DLG_UP_BTN_PLUS_NORMAL,
    ID_DLG_UP_BTN_PLUS_DISABLED,
    ID_DLG_UP_BTN_PLUS_OVER,
    ID_DLG_UP_BTN_PLUS_PUSHED,
};

extern const char SpriteFileDialogUpgradeExp[];

// GENERIC GAME UI
extern const char SpriteFileGameUI[];

enum SpriteIdGameUI : unsigned int
{
    // GOAL COMPLETED
    ID_GAMEUI_GOAL_F1,
    ID_GAMEUI_GOAL_F2,
    ID_GAMEUI_GOAL_F3,
};

extern const char SpriteFileGameUIExp[];

enum SpriteIdGameUIExp : unsigned int
{
    // SCREEN OVERALY BG
    ID_SCREEN_OVERLAY_BG
};

// FACTION SELECTION DIALOG
extern const char SpriteFileFactionSelection[];

enum SpriteIdFactionSelection : unsigned int
{
    // PANELS
    IND_FSEL_MAIN_BG,
    IND_FSEL_PANEL_F1,
    IND_FSEL_PANEL_F2,
    IND_FSEL_PANEL_F3,
    IND_FSEL_PANEL_TXT,
    IND_FSEL_PANEL_ATTR,

    // ATTRIBUTES BAR
    IND_FSEL_BAR0,
    IND_FSEL_BAR1,
    IND_FSEL_BAR2,
    IND_FSEL_BAR3,
    IND_FSEL_BAR4,
    IND_FSEL_BAR5,
    IND_FSEL_BAR6,
    IND_FSEL_BAR7,
    IND_FSEL_BAR8,
    IND_FSEL_BAR9,
    IND_FSEL_BAR10,

    // BACK BUTTON
    IND_FSEL_BACK_NORMAL,
    IND_FSEL_BACK_OVER,
    IND_FSEL_BACK_PUSHED,

    // SELECT BUTTON
    IND_FSEL_SEL_NORMAL,
    IND_FSEL_SEL_OVER,
    IND_FSEL_SEL_PUSHED,
    IND_FSEL_SEL_CHECKED,

    // CONTINUE BUTTON
    IND_FSEL_CONTINUE_NORMAL,
    IND_FSEL_CONTINUE_DISABLED,
    IND_FSEL_CONTINUE_OVER,
    IND_FSEL_CONTINUE_PUSHED,

    // SPECIAL VALUES
    NUM_FSEL_PIPS = IND_FSEL_BAR9 - IND_FSEL_BAR0 + 1
};

// OBJECT ACTION BUTTON
extern const char SpriteFileObjActionButton[];

enum SpriteIdObjActionButton : unsigned int
{
    // BUTTON
    IND_BUTTON_NORMAL,
    IND_BUTTON_DISABLED,
    IND_BUTTON_MOUSE_OVER,
    IND_BUTTON_PUSHED,
    IND_BUTTON_CHECKED,

    // ICONS
    IND_BUTTON_ICON_UNITS,
    IND_BUTTON_ICON_MOVE,
    IND_BUTTON_ICON_ATTACK,
    IND_BUTTON_ICON_CONQUER_CELL,
    IND_BUTTON_ICON_BUILD_WALL,
    IND_BUTTON_ICON_BUILD_STRUCT,
    IND_BUTTON_ICON_MISSION_GOALS,
    IND_BUTTON_ICON_UPGRADE,
    IND_BUTTON_ICON_OPEN_GATE,
    IND_BUTTON_ICON_CLOSE_GATE,
    IND_BUTTON_ICON_CANCEL,
    IND_BUTTON_ICON_HEAL,
    IND_BUTTON_ICON_TRADE,
    IND_BUTTON_ICON_SPAWN,
    IND_BUTTON_ICON_SELF_DESTROY,
    IND_BUTTON_ICON_SET_TARGET,
    IND_BUTTON_ICON_RESEARCH,
    IND_BUTTON_ICON_TECH_TREE,

    // ACTION OPTION BUTTON
    ID_BTN_ACT_OPT_NORMAL,
    ID_BTN_ACT_OPT_DISABLED,
    ID_BTN_ACT_OPT_MOUSE_OVER,
    ID_BTN_ACT_OPT_PUSHED,
    ID_BTN_ACT_OPT_CHECKED,
};


// PANEL SELECTED OBJECT
extern const char SpriteFilePanelSelectedObject[];

enum SpriteIdPanelSelectedObject : unsigned int
{
    // BACKGROUND
    ID_PAN_SELOBJ_BG,

    // VALUE BAR
    ID_PAN_SELOBJ_VALBAR_BG,
    ID_PAN_SELOBJ_VALBAR_BAR,
    ID_PAN_SELOBJ_VALBAR_MARKS,

    // STARS BAR
    ID_PAN_SELOBJ_SBAR_0,
    ID_PAN_SELOBJ_SBAR_1,
    ID_PAN_SELOBJ_SBAR_2,
    ID_PAN_SELOBJ_SBAR_3,
    ID_PAN_SELOBJ_SBAR_4,
    ID_PAN_SELOBJ_SBAR_5,
    ID_PAN_SELOBJ_SBAR_6,
    ID_PAN_SELOBJ_SBAR_7,
    ID_PAN_SELOBJ_SBAR_8,
    ID_PAN_SELOBJ_SBAR_9,
    ID_PAN_SELOBJ_SBAR_10,

    // ICONS
    ID_PAN_SELOBJ_ICON_ENERGY,
    ID_PAN_SELOBJ_ICON_HEALTH,
    ID_PAN_SELOBJ_ICON_EXPERIENCE,

    // BUTTON PANEL
    ID_PAN_SELOBJ_BTN_NORMAL,
    ID_PAN_SELOBJ_BTN_OVER,
    ID_PAN_SELOBJ_BTN_PUSHED,

    // BUTTON CLOSE PANEL
    ID_PAN_SELOBJ_BTN_CLOSE_NORMAL,
    ID_PAN_SELOBJ_BTN_CLOSE_OVER,
    ID_PAN_SELOBJ_BTN_CLOSE_PUSHED,

    // BUTTON ACTION
    ID_PAN_SELOBJ_BTN_ACTION_NORMAL,
    ID_PAN_SELOBJ_BTN_ACTION_DISABLED,
    ID_PAN_SELOBJ_BTN_ACTION_OVER,
    ID_PAN_SELOBJ_BTN_ACTION_PUSHED,
    ID_PAN_SELOBJ_BTN_ACTION_CHECKED,

    // ICONS ACTION
    ID_PAN_SELOBJ_ICON_ACT_ATTACK,
    ID_PAN_SELOBJ_ICON_ACT_MOVE,
    ID_PAN_SELOBJ_ICON_ACT_INFO,
    ID_PAN_SELOBJ_ICON_ACT_UPGRADE,
};

// MAIN MENU
extern const char SpriteFileMainMenu[];

enum SpriteIdMainMenu : unsigned int
{
    // CHANGELOG DIALOG
    IND_MM_BTN_UPDATES,
    IND_MM_BTN_CLOSE,
    IND_MM_BTN_SCROLLBAR,
    IND_MM_DIALOG_UPDATES,
    IND_MM_SCROLLBAR,
};

// MAIN MENU BUTTONS
extern const char SpriteFileMainMenuButtons[];

enum SpriteIdMainMenuButtons : unsigned int
{
    // PRIMARY BUTTON
    IND_MM_BTN1_NORMAL,
    IND_MM_BTN1_DISABLED,
    IND_MM_BTN1_OVER,
    IND_MM_BTN1_PUSHED,
    IND_MM_BTN1_CHECKED,

    // WISHLIST BUTTON
    IND_MM_BTNW_NORMAL,
    IND_MM_BTNW_OVER,
    IND_MM_BTNW_PUSHED,

    // SOCIAL BUTTON
    IND_MM_BTNS_NORMAL,
    IND_MM_BTNS_OVER,
    IND_MM_BTNS_PUSHED,

    // ICONS
    IND_MM_ICON_STEAM,
    IND_MM_ICON_DISCORD,
    IND_MM_ICON_BLUESKY,
    IND_MM_ICON_YOUTUBE,
    IND_MM_ICON_LINKEDIN,

    NUM_MAIN_MENU_SPRITES
};

// PANEL HIT
extern const char SpriteFilePanelHit[];

// MAP PANELS
extern const char SpriteFilePanelMinimap[];

enum SpriteIdMapPanels : unsigned int
{
    // MINIMAP
    IND_MINIMAP_BG,
    IND_MINIMAP_MAP_ELEM,
    IND_MINIMAP_BTN_CLOSE_NORMAL,
    IND_MINIMAP_BTN_CLOSE_OVER,
    IND_MINIMAP_BTN_CLOSE_PUSHED,
    IND_MINIMAP_BTN_U_NORMAL,
    IND_MINIMAP_BTN_U_DISABLED,
    IND_MINIMAP_BTN_U_OVER,
    IND_MINIMAP_BTN_U_PUSHED,
    IND_MINIMAP_BTN_D_NORMAL,
    IND_MINIMAP_BTN_D_DISABLED,
    IND_MINIMAP_BTN_D_OVER,
    IND_MINIMAP_BTN_D_PUSHED,
    IND_MINIMAP_BTN_R_NORMAL,
    IND_MINIMAP_BTN_R_DISABLED,
    IND_MINIMAP_BTN_R_OVER,
    IND_MINIMAP_BTN_R_PUSHED,
    IND_MINIMAP_BTN_L_NORMAL,
    IND_MINIMAP_BTN_L_DISABLED,
    IND_MINIMAP_BTN_L_OVER,
    IND_MINIMAP_BTN_L_PUSHED,
    IND_MINIMAP_CAMERA_BL,
    IND_MINIMAP_CAMERA_TR,
    IND_MINIMAP_CAMERA_TL,
    IND_MINIMAP_CAMERA_BR,
    // MINIMAP BUTTON
    IND_MINIMAP_BUTTON_NORMAL,
    IND_MINIMAP_BUTTON_OVER,
    IND_MINIMAP_BUTTON_PUSHED
};

// MAP UI
extern const char SpriteFileMapUI[];

enum SpriteIdMapUI : unsigned int
{
    // CELL PROGRESS BAR
    IND_CELL_BAR_BG,
    IND_CELL_BAR_F1,
    IND_CELL_BAR_F2,
    IND_CELL_BAR_F3,
    IND_CELL_BAR_F4,
    // ICON COSTS
    IND_ICON_CELL_ENERGY,
    IND_ICON_CELL_MATERIAL
};

// MAP UI
extern const char SpriteFilePanelTurnControl[];

enum SpriteIdPanelTurnControl : unsigned int
{
    // BACKGROUND
    ID_TURN_CONTROL_BG,
    // PROGRESS BAR
    ID_TURN_CONTROL_PB_BG,
    ID_TURN_CONTROL_PB_BAR,
    ID_TURN_CONTROL_PB_MARKS,
    // BUTTON
    ID_TURN_CONTROL_BUTTON_NORMAL,
    ID_TURN_CONTROL_BUTTON_DISABLED,
    ID_TURN_CONTROL_BUTTON_OVER,
    ID_TURN_CONTROL_BUTTON_PUSHED,
    // ICONS
    ID_TURN_CONTROL_ICON,
};

// PLANET MAP
extern const char SpriteFilePlanetMap[];

enum SpriteIdPlanetMap : unsigned int
{
    // PLANET
    IND_PM_PLANET,
    // PLANET CELL
    IND_PM_CELL_UNEXPLORED,
    IND_PM_CELL_UNEXPLORED_SEL,
    IND_PM_CELL_EXPLORED,
    IND_PM_CELL_SELECTED,
    IND_PM_CELL_F1,
    IND_PM_CELL_F1_SEL,
    IND_PM_CELL_F2,
    IND_PM_CELL_F2_SEL,
    IND_PM_CELL_F3,
    IND_PM_CELL_F3_SEL,
    IND_PM_CELL_DISABLED,
    // PLANET MAIN CELL
    IND_PM_MAIN_CELL_UNEXPLORED,
    IND_PM_MAIN_CELL_UNEXPLORED_SEL,
    IND_PM_MAIN_CELL_EXPLORED,
    IND_PM_MAIN_CELL_SELECTED,
    IND_PM_MAIN_CELL_F1,
    IND_PM_MAIN_CELL_F1_SEL,
    IND_PM_MAIN_CELL_F2,
    IND_PM_MAIN_CELL_F2_SEL,
    IND_PM_MAIN_CELL_F3,
    IND_PM_MAIN_CELL_F3_SEL,
    IND_PM_MAIN_CELL_DISABLED,

    // STARS BAR
    IND_PM_STARS_0,
    IND_PM_STARS_1,
    IND_PM_STARS_2,
    IND_PM_STARS_3,
    IND_PM_STARS_4,
    IND_PM_STARS_5,
    IND_PM_STARS_6,
    IND_PM_STARS_7,
    IND_PM_STARS_8,
    IND_PM_STARS_9,
    IND_PM_STARS_10,

    // PIPS BAR
    IND_PM_PIPS_BAR_DIS,
    IND_PM_PIPS_BAR_0,
    IND_PM_PIPS_BAR_1,
    IND_PM_PIPS_BAR_2,
    IND_PM_PIPS_BAR_3,
    IND_PM_PIPS_BAR_4,
    IND_PM_PIPS_BAR_5,
    IND_PM_PIPS_BAR_6,
    IND_PM_PIPS_BAR_7,
    IND_PM_PIPS_BAR_8,
    IND_PM_PIPS_BAR_9,
    IND_PM_PIPS_BAR_10,

    // BUTTON
    IND_PM_BTN_NORMAL,
    IND_PM_BTN_DISABLED,
    IND_PM_BTN_OVER,
    IND_PM_BTN_PRESSED,

    // BUTTON 2
    IND_PM_BTN2_NORMAL,
    IND_PM_BTN2_DISABLED,
    IND_PM_BTN2_OVER,
    IND_PM_BTN2_PRESSED,

    // ICONS
    IND_PM_ICON_MONEY_DIS,
    IND_PM_ICON_ENERGY_DIS,
    IND_PM_ICON_MATERIAL_DIS,
    IND_PM_ICON_DIAMONDS_DIS,
    IND_PM_ICON_BLOBS_DIS,
    IND_PM_ICON_MONEY,
    IND_PM_ICON_ENERGY,
    IND_PM_ICON_MATERIAL,
    IND_PM_ICON_DIAMONDS,
    IND_PM_ICON_BLOBS,

    // BUTTON LEAVE
    IND_PM_BTN3_NORMAL,
    IND_PM_BTN3_DISABLED,
    IND_PM_BTN3_OVER,
    IND_PM_BTN3_PRESSED,
};

// PLANET MAP 2
extern const char SpriteFilePlanetMap2[];

enum SpriteIdPlanetMap2 : unsigned int
{
    // PANELS
    IND_PM_PANEL_NAME,
    IND_PM_PANEL_DATE,
    IND_PM_PANEL_RESOURCES,
    IND_PM_PANEL_ACTIONS,
    IND_PM_PANEL_INFO,
    IND_PM_PANEL_LEAVE
};

// RESOURCES BAR
extern const char SpriteFileResourcesBar[];

enum SpriteIdResourcesBar : unsigned int
{
    // BAR
    IND_RESBAR_BG_L,
    IND_RESBAR_BG_R,

    // MINI BAR
    IND_RESBAR_MINIBAR_BG,
    IND_RESBAR_MINIBAR_VAL,

    // ICONS
    IND_RESBAR_MONEY,
    IND_RESBAR_ENERGY,
    IND_RESBAR_MATERIAL,
    IND_RESBAR_DIAMOND,
    IND_RESBAR_BLOB,
    IND_RESBAR_RESEARCH,
};

extern const char SpriteFileResourcesBarExp[];

// SETTINGS
extern const char SpriteFileDialogSettings[];

enum SpriteIdSettings : unsigned int
{
    // BACKGROUND
    ID_DLG_SETT_BG_L,
    ID_DLG_SETT_BG_R,

    // COMBO BOX
    ID_DLG_SETT_CB_NORMAL,
    ID_DLG_SETT_CB_DISABLED,
    ID_DLG_SETT_CB_OVER,
    ID_DLG_SETT_CB_PUSHED,
    ID_DLG_SETT_CBI_NORMAL,
    ID_DLG_SETT_CBI_DISABLED,
    ID_DLG_SETT_CBI_OVER,
    ID_DLG_SETT_CBI_PUSHED,

    // CHECK BOX
    ID_DLG_SETT_CHB_NORMAL,
    ID_DLG_SETT_CHB_DISABLED,
    ID_DLG_SETT_CHB_OVER,
    ID_DLG_SETT_CHB_PUSHED,
    ID_DLG_SETT_CHB_CHECKED,

    // SLIDER
    ID_DLG_SETT_SLIDER_BG,
    ID_DLG_SETT_SLIDER_BAR,
    ID_DLG_SETT_SLIDER_BUTTON,
};

// SETTINGS - EXPANDABLE TEXTURES
extern const char SpriteFileDialogSettingsExp[];

// TOOLTIPS
extern const char SpriteFileTooltips[];

enum SpriteIdTooltips : unsigned int
{
    // RESOURCE BAR TOOLTIP
    ID_TOOLTIP_RES_BAR_BG,
    // GAME TOOLTIP
    ID_TOOLTIP_GAME_BG_L,
    ID_TOOLTIP_GAME_BG_R,
};

// TOOLTIPS - EXPANDABLE TEXTURE
extern const char SpriteFileTooltipsExp[];

enum SpriteIdTooltipsExp : unsigned int
{
    // GAME TOOLTIP
    ID_TOOLTIP_GAME_BG_C,
};

// SHARED UI GRAPHICS
extern const char SpriteFileUIShared[];

enum SpriteIdUIShared : unsigned int
{
    // ICONS WHITE RESOURCES 24x24
    ID_UIS_ICON_W_RES_MONEY_24,
    ID_UIS_ICON_W_RES_ENERGY_24,
    ID_UIS_ICON_W_RES_MATERIAL_24,
    ID_UIS_ICON_W_RES_DIAMONDS_24,
    ID_UIS_ICON_W_RES_BLOBS_24,
    ID_UIS_ICON_W_RES_RESEARCH_24,
    // ICONS COLOR RESOURCES 24x24
    ID_UIS_ICON_C_RES_MONEY_24,
    ID_UIS_ICON_C_RES_ENERGY_24,
    ID_UIS_ICON_C_RES_MATERIAL_24,
    ID_UIS_ICON_C_RES_DIAMONDS_24,
    ID_UIS_ICON_C_RES_BLOBS_24,
    ID_UIS_ICON_C_RES_RESEARCH_24,
    // ICONS WHITE RESOURCES 16x16
    ID_UIS_ICON_W_RES_MONEY_16,
    ID_UIS_ICON_W_RES_ENERGY_16,
    ID_UIS_ICON_W_RES_MATERIAL_16,
    ID_UIS_ICON_W_RES_DIAMONDS_16,
    ID_UIS_ICON_W_RES_BLOBS_16,
    ID_UIS_ICON_W_RES_RESEARCH_16,
    // ICONS COLOR RESOURCES 16x16
    ID_UIS_ICON_C_RES_MONEY_16,
    ID_UIS_ICON_C_RES_ENERGY_16,
    ID_UIS_ICON_C_RES_MATERIAL_16,
    ID_UIS_ICON_C_RES_DIAMONDS_16,
    ID_UIS_ICON_C_RES_BLOBS_16,
    ID_UIS_ICON_C_RES_RESEARCH_16,
    // WARNING ICON
    ID_UIS_ICON_WARNING,
    // BUTTON DIALOG CLOSE
    ID_BTN_DLG_CLOSE_NORMAL,
    ID_BTN_DLG_CLOSE_DISABLED,
    ID_BTN_DLG_CLOSE_OVER,
    ID_BTN_DLG_CLOSE_PUSHED,
    // SLIDER DIALOG
    ID_SLIDER_DLG_BG,
    ID_SLIDER_DLG_BAR,
    ID_SLIDER_DLG_BTN,
    // VALUE BAR
    ID_VALBAR_BG,
    ID_VALBAR_BAR,
    ID_VALBAR_MARKS,
    //CHECKBOX
    ID_CHECKBOX_NORMAL,
    ID_CHECKBOX_DISABLED,
    ID_CHECKBOX_CHECKED,
    // BUTTON DIALOG STANDARD
    ID_DLG_BTN_STD_NORMAL,
    ID_DLG_BTN_STD_DISABLED,
    ID_DLG_BTN_STD_OVER,
    ID_DLG_BTN_STD_PUSHED,
    // STARS BAR
    ID_STARS_BAR_0,
    ID_STARS_BAR_1,
    ID_STARS_BAR_2,
    ID_STARS_BAR_3,
    ID_STARS_BAR_4,
    ID_STARS_BAR_5,
    ID_STARS_BAR_6,
    ID_STARS_BAR_7,
    ID_STARS_BAR_8,
    ID_STARS_BAR_9,
    ID_STARS_BAR_10,
    // BUTTON DIALOG OK
    ID_DLG_BTN_OK_NORMAL,
    ID_DLG_BTN_OK_DISABLED,
    ID_DLG_BTN_OK_OVER,
    ID_DLG_BTN_OK_PUSHED,
    // ATTRIBUTES PANEL
    ID_PANEL_ATT_ON,
    ID_PANEL_ATT_OFF,
    // ATTRIBUTES BAR
    ID_ATT_BAR0,
    ID_ATT_BAR1,
    ID_ATT_BAR2,
    ID_ATT_BAR3,
    ID_ATT_BAR4,
    ID_ATT_BAR5,
    ID_ATT_BAR6,
    ID_ATT_BAR7,
    ID_ATT_BAR8,
    ID_ATT_BAR9,
    ID_ATT_BAR10,
    // BUTTON TAB
    ID_BTN_TAB_NORMAL,
    ID_BTN_TAB_DISABLED,
    ID_BTN_TAB_OVER,
    ID_BTN_TAB_PUSHED,
    ID_BTN_TAB_CHECKED,
};

// UNIT QUICK SELECTION
extern const char SpriteFileUnitQuickSel[];

enum SpriteIdUnitQuickSel : unsigned int
{
    // BUTTON BG
    IND_UQS_BG_NORMAL,
    IND_UQS_BG_DISABLED,
    IND_UQS_BG_MOUSE_OVER,
    IND_UQS_BG_PUSHED,
    IND_UQS_BG_CHECKED,

    // ICONS
    IND_UQS_ICON_ENERGY,
    IND_UQS_ICON_HEALTH,

    // UNITS F1
    IND_UQS_UNIT1_F1,
    IND_UQS_UNIT2_F1,
    IND_UQS_UNIT3_F1,
    IND_UQS_UNIT4_F1,
    IND_UQS_UNIT5_F1,
    IND_UQS_UNIT6_F1,
    IND_UQS_UNIT7_F1,
    // UNITS F2
    IND_UQS_UNIT1_F2,
    IND_UQS_UNIT2_F2,
    IND_UQS_UNIT3_F2,
    IND_UQS_UNIT4_F2,
    IND_UQS_UNIT5_F2,
    IND_UQS_UNIT6_F2,
    IND_UQS_UNIT7_F2,
    // UNITS F3
    IND_UQS_UNIT1_F3,
    IND_UQS_UNIT2_F3,
    IND_UQS_UNIT3_F3,
    IND_UQS_UNIT4_F3,
    IND_UQS_UNIT5_F3,
    IND_UQS_UNIT6_F3,
    IND_UQS_UNIT7_F3,

    NUM_UQS_UNIT_SPRITE_PER_FACTION = IND_UQS_UNIT1_F2 - IND_UQS_UNIT1_F1
};

// TUTORIAL
extern const char SpriteFileTutorial[];

enum SpriteIdTutorial : unsigned int
{
    // AREA CORNERS
    IND_TUT_AREA_CORNER_TL,
    IND_TUT_AREA_CORNER_TR,
    IND_TUT_AREA_CORNER_BL,
    IND_TUT_AREA_CORNER_BR,

    // INFO PANEL CORNERS
    IND_TUT_PANEL_INFO_CORNER_TL,
    IND_TUT_PANEL_INFO_CORNER_TR,
    IND_TUT_PANEL_INFO_CORNER_BL,
    IND_TUT_PANEL_INFO_CORNER_BR,
};

// TUTORIAL - EXPANDABLE TEXTURES
extern const char SpriteFileTutorialExp[];

enum SpriteIdTutorialExp : unsigned int
{
    // INFO PANEL SIDES AND CENTER
    IND_TUT_PANEL_INFO_T,
    IND_TUT_PANEL_INFO_B,
    IND_TUT_PANEL_INFO_L,
    IND_TUT_PANEL_INFO_R,
    IND_TUT_PANEL_INFO_BG,
};

} // namespace game
